version: '2'
  services:
    phpschool:
  build: ./
  volumes:
    - /path/to/phpSchool/projectfiles:/phpschool/projectfiles:rw
  #restart: always
  environment:
    - TERM=xterm
  command: tail -f /dev/null
